/*
 * Connector Service Fleet Manager Admin APIs
 *
 * Connector Service Fleet Manager Admin is a Rest API to manage connector clusters.
 *
 * API version: 0.0.3
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package private

// ConnectorAvailableOperatorUpgrade An available operator upgrade for a connector
type ConnectorAvailableOperatorUpgrade struct {
	ConnectorId     string                                    `json:"connector_id,omitempty"`
	Namespace       string                                    `json:"namespace,omitempty"`
	ConnectorTypeId string                                    `json:"connector_type_id,omitempty"`
	Channel         string                                    `json:"channel,omitempty"`
	Operator        ConnectorAvailableOperatorUpgradeOperator `json:"operator,omitempty"`
}
