/*
 * Connector Service Fleet Manager Admin APIs
 *
 * Connector Service Fleet Manager Admin is a Rest API to manage connector clusters.
 *
 * API version: 0.0.3
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package private

// ConnectorCluster Schema for the request to update a data plane cluster's status
type ConnectorCluster struct {
	Id       string                        `json:"id,omitempty"`
	Kind     string                        `json:"kind,omitempty"`
	Href     string                        `json:"href,omitempty"`
	Metadata ConnectorClusterAllOfMetadata `json:"metadata,omitempty"`
	Status   string                        `json:"status,omitempty"`
}
