/*
 * Connector Service Fleet Manager Admin APIs
 *
 * Connector Service Fleet Manager Admin is a Rest API to manage connector clusters.
 *
 * API version: 0.0.3
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package private

// ServiceAccount struct for ServiceAccount
type ServiceAccount struct {
	ClientId     string `json:"client_id"`
	ClientSecret string `json:"client_secret"`
}
