/*
 * Connector Service Fleet Manager Admin APIs
 *
 * Connector Service Fleet Manager Admin is a Rest API to manage connector clusters.
 *
 * API version: 0.0.3
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package private

// ConnectorNamespaceWithTenantRequest struct for ConnectorNamespaceWithTenantRequest
type ConnectorNamespaceWithTenantRequest struct {
	Name        string                                     `json:"name"`
	Annotations []ConnectorNamespaceRequestMetaAnnotations `json:"annotations,omitempty"`
	ClusterId   string                                     `json:"cluster_id,omitempty"`
	Tenant      ConnectorNamespaceTenant                   `json:"tenant,omitempty"`
}
