/*
 * Connector Service Fleet Manager Admin APIs
 *
 * Connector Service Fleet Manager Admin is a Rest API to manage connector clusters.
 *
 * API version: 0.0.3
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package private

// ConnectorNamespaceList struct for ConnectorNamespaceList
type ConnectorNamespaceList struct {
	Kind  string               `json:"kind"`
	Page  int32                `json:"page"`
	Size  int32                `json:"size"`
	Total int32                `json:"total"`
	Items []ConnectorNamespace `json:"items"`
}
