/*
 * Connector Service Fleet Manager Admin APIs
 *
 * Connector Service Fleet Manager Admin is a Rest API to manage connector clusters.
 *
 * API version: 0.0.3
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package private

// ConnectorAdminRequest struct for ConnectorAdminRequest
type ConnectorAdminRequest struct {
	DesiredState ConnectorDesiredState `json:"desired_state"`
}
