common:
  - pkg/**/*
  - test/**/*
  - openapi/templates/**/*
  - scripts/**/*
dinosaur:
  - internal/dinosaur/**/*
  - openapi/fleet*
  - cmd/fleet*
connector:
  - internal/connector/**/*
  - openapi/connector*
github:
  - .github/**/*
