common:
  - pkg/**/*
  - test/**/*
  - openapi/templates/**/*
  - scripts/**/*
kafka:
  - internal/kafka/**/*
  - openapi/kas*
  - cmd/kas*
connector:
  - internal/connector/**/*
  - openapi/connector*
github:
  - .github/**/*