"internal/connector/**/*":
  - valdar
  - dhirajsb
"internal/dinosaur/**/*":
  - pb82
  - machi1990
  - pawelpaszki
  - JameelB
  - miguelsorianod
  - ziccardi
"pkg/**/*":
  - valdar
  - dhirajsb
  - pb82
  - machi1990
  - pawelpaszki
  - JameelB
  - miguelsorianod
  - ziccardi
"test/**/*":
  - valdar
  - dhirajsb
  - pb82
  - machi1990
  - pawelpaszki
  - JameelB
  - miguelsorianod
  - ziccardi
".github/**/*":
  - pb82
  - machi1990
  - pawelpaszki
  - JameelB
  - miguelsorianod
  - ziccardi
