run:
  skip-dirs:
    - pkg/api/openapi
    - pkg/api/private/openapi
    - pkg/api/connector/openapi
    - pkg/api/connector_catalog/openapi
  # timeout for analysis, e.g. 30s, 5m, default is 1m
  timeout: 10m
