// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package services

import (
	"github.com/bf2fc6cc711aee1a0c2a/kas-fleet-manager/internal/kafka/internal/api/dbapi"
	"github.com/bf2fc6cc711aee1a0c2a/kas-fleet-manager/pkg/api"
	serviceError "github.com/bf2fc6cc711aee1a0c2a/kas-fleet-manager/pkg/errors"
	"sync"
)

// Ensure, that ClusterPlacementStrategyMock does implement ClusterPlacementStrategy.
// If this is not the case, regenerate this file with moq.
var _ ClusterPlacementStrategy = &ClusterPlacementStrategyMock{}

// ClusterPlacementStrategyMock is a mock implementation of ClusterPlacementStrategy.
//
// 	func TestSomethingThatUsesClusterPlacementStrategy(t *testing.T) {
//
// 		// make and configure a mocked ClusterPlacementStrategy
// 		mockedClusterPlacementStrategy := &ClusterPlacementStrategyMock{
// 			FindClusterFunc: func(kafka *dbapi.KafkaRequest) (*api.Cluster, *serviceError.ServiceError) {
// 				panic("mock out the FindCluster method")
// 			},
// 		}
//
// 		// use mockedClusterPlacementStrategy in code that requires ClusterPlacementStrategy
// 		// and then make assertions.
//
// 	}
type ClusterPlacementStrategyMock struct {
	// FindClusterFunc mocks the FindCluster method.
	FindClusterFunc func(kafka *dbapi.KafkaRequest) (*api.Cluster, *serviceError.ServiceError)

	// calls tracks calls to the methods.
	calls struct {
		// FindCluster holds details about calls to the FindCluster method.
		FindCluster []struct {
			// Kafka is the kafka argument value.
			Kafka *dbapi.KafkaRequest
		}
	}
	lockFindCluster sync.RWMutex
}

// FindCluster calls FindClusterFunc.
func (mock *ClusterPlacementStrategyMock) FindCluster(kafka *dbapi.KafkaRequest) (*api.Cluster, *serviceError.ServiceError) {
	if mock.FindClusterFunc == nil {
		panic("ClusterPlacementStrategyMock.FindClusterFunc: method is nil but ClusterPlacementStrategy.FindCluster was just called")
	}
	callInfo := struct {
		Kafka *dbapi.KafkaRequest
	}{
		Kafka: kafka,
	}
	mock.lockFindCluster.Lock()
	mock.calls.FindCluster = append(mock.calls.FindCluster, callInfo)
	mock.lockFindCluster.Unlock()
	return mock.FindClusterFunc(kafka)
}

// FindClusterCalls gets all the calls that were made to FindCluster.
// Check the length with:
//     len(mockedClusterPlacementStrategy.FindClusterCalls())
func (mock *ClusterPlacementStrategyMock) FindClusterCalls() []struct {
	Kafka *dbapi.KafkaRequest
} {
	var calls []struct {
		Kafka *dbapi.KafkaRequest
	}
	mock.lockFindCluster.RLock()
	calls = mock.calls.FindCluster
	mock.lockFindCluster.RUnlock()
	return calls
}
