/*
 * Dinosaur Service Fleet Manager Admin APIs
 *
 * The admin APIs for the fleet manager of Dinosaur service
 *
 * API version: 0.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package private

// DinosaurUpdateRequest struct for DinosaurUpdateRequest
type DinosaurUpdateRequest struct {
	StrimziVersion  string `json:"strimzi_version,omitempty"`
	DinosaurVersion string `json:"dinosaur_version,omitempty"`
}
