openapi: 3.0.0
info:
  title: Dinosaur Service Fleet Manager Admin APIs
  description: The admin APIs for the fleet manager of Dinosaur service
  version: 0.0.2
servers:
  - url: https://api.openshift.com
    description: Main (production) server
  - url: https://api.stage.openshift.com
    description: Staging server
  - url: http://localhost:8000
    description: localhost
  - url: /
    description: current domain
tags:
  - name: Admin APIs
    description: ""

paths:
  '/api/dinosaurs_mgmt/v1/admin/dinosaurs':
    get:
      summary: Returns a list of Dinosaurs
      operationId: getDinosaurs
      security:
        - Bearer: []
      responses:
        "200":
          description: Return a list of Dinosaur instances. This endpoint will return all Dinosaur instances that are stored in the database and the are not filtered based on user ids or org ids.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DinosaurList'
        "400":
          description: Bad request
          content:
            application/json:
              schema:
                $ref: 'fleet-manager.yaml#/components/schemas/Error'
        "401":
          description: Auth token is invalid
          content:
            application/json:
              schema:
                $ref: 'fleet-manager.yaml#/components/schemas/Error'
        "403":
          description: User is not authorised to access the service
          content:
            application/json:
              schema:
                $ref: 'fleet-manager.yaml#/components/schemas/Error'
        "500":
          description: Unexpected error occurred
          content:
            application/json:
              schema:
                $ref: 'fleet-manager.yaml#/components/schemas/Error'
      parameters:
        - $ref: 'fleet-manager.yaml#/components/parameters/page'
        - $ref: 'fleet-manager.yaml#/components/parameters/size'
        - $ref: 'fleet-manager.yaml#/components/parameters/orderBy'
        - $ref: 'fleet-manager.yaml#/components/parameters/search'
  '/api/dinosaurs_mgmt/v1/admin/dinosaurs/{id}':
    get:
      summary: Return the details of Dinosaur instance by id
      parameters:
        - $ref: "fleet-manager.yaml#/components/parameters/id"
      security:
        - Bearer: []
      operationId: getDinosaurById
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Dinosaur'
          description: Dinosaur found by ID
        "401":
          description: Auth token is invalid
          content:
            application/json:
              schema:
                $ref: 'fleet-manager.yaml#/components/schemas/Error'
        "403":
          description: User is not authorised to access the service
          content:
            application/json:
              schema:
                $ref: 'fleet-manager.yaml#/components/schemas/Error'
        "404":
          description: No Dinosaur found with the specified ID
          content:
            application/json:
              schema:
                $ref: 'fleet-manager.yaml#/components/schemas/Error'
        "500":
          description: Unexpected error occurred
          content:
            application/json:
              schema:
                $ref: 'fleet-manager.yaml#/components/schemas/Error'
    patch:
      summary: Update a Dinosaur instance by id
      parameters:
        - $ref: "fleet-manager.yaml#/components/parameters/id"
      security:
        - Bearer: []
      operationId: updateDinosaurById
      requestBody:
        description: Dinosaur update data
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DinosaurUpdateRequest'
        required: true
      responses:
        "200":
          description: Dinosaur updated by ID
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Dinosaur'
        "400":
          description: Bad request
          content:
            application/json:
              schema:
                $ref: 'fleet-manager.yaml#/components/schemas/Error'
        "401":
          description: Auth token is invalid
          content:
            application/json:
              schema:
                $ref: 'fleet-manager.yaml#/components/schemas/Error'
        "403":
          description: User is not authorised to access the service
          content:
            application/json:
              schema:
                $ref: 'fleet-manager.yaml#/components/schemas/Error'
        "404":
          description: No Dinosaur found with the specified ID
          content:
            application/json:
              schema:
                $ref: 'fleet-manager.yaml#/components/schemas/Error'
        "500":
          description: Unexpected error occurred
          content:
            application/json:
              schema:
                $ref: 'fleet-manager.yaml#/components/schemas/Error'
    delete:
      summary: Delete a Dinosaur by ID
      parameters:
        - $ref: "fleet-manager.yaml#/components/parameters/id"
        - in: query
          name: async
          description: Perform the action in an asynchronous manner
          schema:
            type: boolean
          required: true
      security:
        - Bearer: [ ]
      operationId: deleteDinosaurById
      responses:
        "200":
          description: Dinosaur updated by ID
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Dinosaur'
        "401":
          description: Auth token is invalid
          content:
            application/json:
              schema:
                $ref: 'fleet-manager.yaml#/components/schemas/Error'
        "403":
          description: User is not authorised to access the service
          content:
            application/json:
              schema:
                $ref: 'fleet-manager.yaml#/components/schemas/Error'
        "404":
          description: No Dinosaur found with the specified ID
          content:
            application/json:
              schema:
                $ref: 'fleet-manager.yaml#/components/schemas/Error'
        "500":
          description: Unexpected error occurred
          content:
            application/json:
              schema:
                $ref: 'fleet-manager.yaml#/components/schemas/Error'

components:
  schemas:
    Dinosaur:
      allOf:
        - $ref: 'fleet-manager.yaml#/components/schemas/ObjectReference'
        - required:
          - multi_az
          - dinosaur_operator_upgrading
          - dinosaur_upgrading
        - type: object
          properties:
            status:
              description: "Values: [accepted, preparing, provisioning, ready, failed, deprovision, deleting] "
              type: string
            cloud_provider:
              description: "Name of Cloud used to deploy. For example AWS"
              type: string
            multi_az:
              type: boolean
            region:
              description: "Values will be regions of specific cloud provider. For example: us-east-1 for AWS"
              type: string
            owner:
              type: string
            name:
              type: string
            host:
              type: string
            created_at:
              format: date-time
              type: string
            updated_at:
              format: date-time
              type: string
            failed_reason:
              type: string
            actual_dinosaur_version:
              type: string
            actual_dinosaur_operator_version:
              type: string
            desired_dinosaur_version:
              type: string
            desired_dinosaur_operator_version:
              type: string
            dinosaur_upgrading:
              type: boolean
            dinosaur_operator_upgrading:
              type: boolean
            organisation_id:
              type: string
            subscription_id:
              type: string
            owner_account_id:
              type: string
            account_number:
              type: string
            instance_type:
              type: string
            quota_type:
              type: string
            routes:
              type: array
              items:
                type: object
                properties:
                  domain:
                    type: string
                  router:
                    type: string
            routes_created:
              type: boolean
            cluster_id:
              type: string
            namespace:
              type: string
    DinosaurList:
      allOf:
        - $ref: "fleet-manager.yaml#/components/schemas/List"
        - type: object
          properties:
            items:
              type: array
              items:
                allOf:
                  - $ref: "#/components/schemas/Dinosaur"

    DinosaurUpdateRequest:
      type: object
      properties:
        # for now only support updating the following fields. May add more when use cases arise.
        dinosaur_operator_version:
          type: string
        dinosaur_version:
          type: string

  securitySchemes:
    Bearer:
      scheme: bearer
      bearerFormat: JWT
      type: http
