/*
 * Connector Management API
 *
 * Connector Management API is a REST API to manage connectors.
 *
 * API version: 0.1.0
 * Contact: rhosak-support@redhat.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package public

// ProcessorRequest struct for ProcessorRequest
type ProcessorRequest struct {
	Name            string                `json:"name"`
	NamespaceId     string                `json:"namespace_id"`
	ProcessorTypeId string                `json:"processor_type_id"`
	Channel         Channel               `json:"channel,omitempty"`
	DesiredState    ProcessorDesiredState `json:"desired_state"`
	// Name-value string annotations for resource
	Annotations    map[string]string       `json:"annotations,omitempty"`
	Kafka          KafkaConnectionSettings `json:"kafka"`
	ServiceAccount ServiceAccount          `json:"service_account"`
	Definition     map[string]interface{}  `json:"definition,omitempty"`
	ErrorHandler   ErrorHandler            `json:"error_handler,omitempty"`
}
