/*
 * Connector Service Fleet Manager
 *
 * Connector Service Fleet Manager is a Rest API to manage connectors.
 *
 * API version: 0.1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package public

// ServiceConnectionSettings struct for ServiceConnectionSettings
type ServiceConnectionSettings struct {
	Id           string `json:"id"`
	ClientId     string `json:"client_id"`
	ClientSecret string `json:"client_secret"`
	Url          string `json:"url,omitempty"`
}
