/*
 * Connector Service Fleet Manager
 *
 * Connector Service Fleet Manager is a Rest API to manage connectors.
 *
 * API version: 0.0.3
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package public

// ConnectorAvailableOperatorUpgradeOperator struct for ConnectorAvailableOperatorUpgradeOperator
type ConnectorAvailableOperatorUpgradeOperator struct {
	AssignedId  string `json:"assigned_id,omitempty"`
	AvailableId string `json:"available_id,omitempty"`
}
