/*
 * Connector Management API
 *
 * Connector Management API is a REST API to manage connectors.
 *
 * API version: 0.1.0
 * Contact: rhosak-support@redhat.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package public

// ConnectorClusterStatusStatus struct for ConnectorClusterStatusStatus
type ConnectorClusterStatusStatus struct {
	State ConnectorClusterState `json:"state,omitempty"`
	Error string                `json:"error,omitempty"`
}
