/*
 * Connector Service Fleet Manager
 *
 * Connector Service Fleet Manager is a Rest API to manage connectors.
 *
 * API version: 0.1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package public

// ConnectorClusterRequest Schema for the request to update a data plane cluster's name
type ConnectorClusterRequest struct {
	Name string `json:"name,omitempty"`
}
