/*
 * Connector Management API
 *
 * Connector Management API is a REST API to manage connectors.
 *
 * API version: 0.1.0
 * Contact: rhosak-support@redhat.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package public

// ErrorHandlerDeadLetterQueueDeadLetterQueue struct for ErrorHandlerDeadLetterQueueDeadLetterQueue
type ErrorHandlerDeadLetterQueueDeadLetterQueue struct {
	// The name of the Kafka topic that serves as a destination for messages which were not processed correctly due to an error.
	Topic string `json:"topic,omitempty"`
}
