/*
 * Connector Management API
 *
 * Connector Management API is a REST API to manage connectors.
 *
 * API version: 0.1.0
 * Contact: rhosak-support@redhat.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package public

// ConnectorNamespaceState the model 'ConnectorNamespaceState'
type ConnectorNamespaceState string

// List of ConnectorNamespaceState
const (
	CONNECTORNAMESPACESTATE_DISCONNECTED ConnectorNamespaceState = "disconnected"
	CONNECTORNAMESPACESTATE_READY        ConnectorNamespaceState = "ready"
	CONNECTORNAMESPACESTATE_DELETING     ConnectorNamespaceState = "deleting"
	CONNECTORNAMESPACESTATE_DELETED      ConnectorNamespaceState = "deleted"
)
