/*
 * Connector Service Fleet Manager
 *
 * Connector Service Fleet Manager is a Rest API to manage connectors.
 *
 * API version: 0.1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package public

// ConnectorNamespaceTenantOrganisation struct for ConnectorNamespaceTenantOrganisation
type ConnectorNamespaceTenantOrganisation struct {
	Kind           string `json:"kind,omitempty"`
	OrganisationId string `json:"organisation_id,omitempty"`
}
