/*
 * Connector Service Fleet Manager
 *
 * Connector Service Fleet Manager is a Rest API to manage connectors.
 *
 * API version: 0.1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package public

// ConnectorMeta struct for ConnectorMeta
type ConnectorMeta struct {
	Name               string                `json:"name"`
	ConnectorTypeId    string                `json:"connector_type_id"`
	Channel            Channel               `json:"channel,omitempty"`
	DeploymentLocation DeploymentLocation    `json:"deployment_location"`
	DesiredState       ConnectorDesiredState `json:"desired_state"`
}
