/*
 * Managed Service API
 *
 * Managed Service API
 *
 * API version: 0.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// Metric struct for Metric
type Metric struct {
	Metric map[string]string `json:"metric,omitempty"`
	Values []Values          `json:"values,omitempty"`
}
