/*
 * Managed Service API
 *
 * Managed Service API
 *
 * API version: 0.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// MetricsQueryInstantList struct for MetricsQueryInstantList
type MetricsQueryInstantList struct {
	Kind  string         `json:"kind,omitempty"`
	Id    string         `json:"id,omitempty"`
	Items []QueryInstant `json:"items,omitempty"`
}
