/*
 * Kafka Service Fleet Manager
 *
 * Kafka Service Fleet Manager is a Rest API to manage kafka instances and connectors.
 *
 * API version: 0.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// InstantQuery struct for InstantQuery
type InstantQuery struct {
	Metric    map[string]string `json:"metric,omitempty"`
	Timestamp int64             `json:"Timestamp,omitempty"`
	Value     float64           `json:"Value"`
}
