/*
 * Kafka Service Fleet Manager
 *
 * Kafka Service Fleet Manager is a Rest API to manage kafka instances and connectors.
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// Values struct for Values
type Values struct {
	Timestamp int64   `json:"Timestamp,omitempty"`
	Value     float64 `json:"Value"`
}
