/*
 * OCM Example Service API
 *
 * OCM Example Service API
 *
 * API version: 0.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"time"
)

type Dinosaur struct {
	Id        string    `json:"id,omitempty"`
	Kind      string    `json:"kind,omitempty"`
	Href      string    `json:"href,omitempty"`
	Species   string    `json:"species,omitempty"`
	CreatedAt time.Time `json:"created_at,omitempty"`
	UpdatedAt time.Time `json:"updated_at,omitempty"`
}
