/*
 * Managed Service API
 *
 * Managed Service API
 *
 * API version: 0.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// QueryInstant struct for QueryInstant
type QueryInstant struct {
	Metric    map[string]string `json:"metric,omitempty"`
	Timestamp int64             `json:"Timestamp,omitempty"`
	Value     float64           `json:"Value"`
}
