/*
 * Kafka Service Fleet Manager
 *
 * Kafka Service Fleet Manager is a Rest API to manage Kafka instances and connectors.
 *
 * API version: 1.1.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// ServiceAccountList struct for ServiceAccountList
type ServiceAccountList struct {
	Kind  string                   `json:"kind"`
	Items []ServiceAccountListItem `json:"items"`
}
