{
 "title": "Fleet Manager SLOs",
 "tags": [ "fleet-manager" ],
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "API Availability",
   "type": "graph",
   "gridPos": { "h": 15, "w": 9, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "(sum(rate(haproxy_backend_http_responses_total{route=\"fleet-manager\",exported_namespace=\"managed-services-production\",code!=\"5xx\"}[5m]))/sum(rate(haproxy_backend_http_responses_total{route=\"fleet-manager\",exported_namespace=\"managed-services-production\"}[5m]))) * 100",
     "legendFormat": "fleet-manager"
    }
   ]
  },
  {
   "title": "SLOs",
   "type": "text",
   "description": "Calculated over the last 28 days\n\n",
   "gridPos": { "h": 3, "w": 4, "x": 9, "y": 0 },
   "options": {
    "content": "Calculated over the last 28 days"
   }
  },
  {
   "title": "API Latency",
   "type": "graph",
   "gridPos": { "h": 15, "w": 9, "x": 13, "y": 0 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(api_inbound_request_duration_bucket{job=\"fleet-manager-metrics\",namespace=\"managed-services-production\",code!~\"5..\"}[5m])) by (le))",
     "legendFormat": "p99"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(api_inbound_request_duration_bucket{job=\"fleet-manager-metrics\",namespace=\"managed-services-production\",code!~\"5..\"}[5m])) by (le))",
     "legendFormat": "p90"
    }
   ]
  },
  {
   "title": "API Availability (95%) ",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 9, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(rate(haproxy_backend_http_responses_total{route=\"fleet-manager\",exported_namespace=\"managed-services-production\",code!=\"5xx\"}[28d]))/sum(rate(haproxy_backend_http_responses_total{route=\"fleet-manager\",exported_namespace=\"managed-services-production\"}[28d]))) * 100",
     "legendFormat": "Create Operation"
    }
   ]
  },
  {
   "title": "API Latency p99 < 1s",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 9, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "(sum(rate(api_inbound_request_duration_bucket{job=\"fleet-manager-metrics\",namespace=\"managed-services-production\",le=\"1\",code!~\"5..\"}[$__range]))/sum(rate(api_inbound_request_duration_count{job=\"fleet-manager-metrics\",namespace=\"managed-services-production\"}[$__range]))) * 100"
    }
   ]
  },
  {
   "title": "API Latency p90 < 0.1s",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 9, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "(sum(rate(api_inbound_request_duration_bucket{job=\"fleet-manager-metrics\",namespace=\"managed-services-production\",le=\"0.1\",code!~\"5..\"}[$__range]))/sum(rate(api_inbound_request_duration_count{job=\"fleet-manager-metrics\",namespace=\"managed-services-production\"}[$__range]))) * 100"
    }
   ]
  },
  {
   "title": "Pineapple Cluster Lifecycle Correctness",
   "type": "graph",
   "gridPos": { "h": 14, "w": 9, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(rate(fleet_manager_pineapple_operations_success_count{job=\"fleet-manager-metrics\",namespace=\"managed-services-production\",operation=\"create\"}[5m]))/sum(rate(fleet_manager_pineapple_operations_total_count{job=\"fleet-manager-metrics\",namespace=\"managed-services-production\",operation=\"create\"}[5m]))",
     "legendFormat": "Create Operation"
    },
    {
     "expr": "sum(rate(fleet_manager_pineapple_operations_success_count{job=\"fleet-manager-metrics\",namespace=\"managed-services-production\",operation=\"delete\"}[5m]))/sum(rate(fleet_manager_pineapple_operations_total_count{job=\"fleet-manager-metrics\",namespace=\"managed-services-production\",operation=\"delete\"}[5m]))",
     "legendFormat": "Delete Operation"
    }
   ]
  },
  {
   "title": "Pineapple Correctness (Create)",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 9, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(fleet_manager_pineapple_operations_success_count{job=\"fleet-manager-metrics\",namespace=\"managed-services-production\",operation=~\"create\"}[28d]))/sum(rate(fleet_manager_pineapple_operations_total_count{job=\"fleet-manager-metrics\",namespace=\"managed-services-production\",operation=~\"create\"}[28d])) * 100",
     "legendFormat": "Create Operation"
    }
   ]
  },
  {
   "title": "Pineapple Cluster Provisioning Latency",
   "type": "graph",
   "gridPos": { "h": 14, "w": 9, "x": 13, "y": 15 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(fleet_manager_worker_pineapple_duration_bucket{job=\"fleet-manager-metrics\",namespace=\"managed-services-production\",jobType=\"pineapple_create\"}[5m])) by (le))",
     "legendFormat": "p99-create"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(fleet_manager_worker_pineapple_duration_bucket{job=\"fleet-manager-metrics\",namespace=\"managed-services-production\",jobType=\"pineapple_create\"}[5m])) by (le))",
     "legendFormat": "p90-create"
    }
   ]
  },
  {
   "title": "Pineapple Correctness (Delete)",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 9, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(fleet_manager_pineapple_operations_success_count{job=\"fleet-manager-metrics\",namespace=\"managed-services-production\",operation=~\"delete\"}[28d]))/sum(rate(fleet_manager_pineapple_operations_total_count{job=\"fleet-manager-metrics\",namespace=\"managed-services-production\",operation=~\"delete\"}[28d])) * 100",
     "legendFormat": "Create Operation"
    }
   ]
  },
  {
   "title": "Pineapple Latency p90 < 900s",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 9, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "(sum(rate(fleet_manager_worker_pineapple_duration_bucket{job=\"fleet-manager-metrics\",namespace=\"managed-services-production\",le=\"900\",jobType=\"pineapple_create\"}[28d]))/sum(rate(fleet_manager_worker_pineapple_duration_count{job=\"fleet-manager-metrics\",namespace=\"managed-services-production\",jobType=\"pineapple_create\"}[28d]))) * 100",
     "legendFormat": "Create Operation"
    }
   ]
  },
  {
   "title": "Pineapple Latency p99 < 1800s",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 9, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "(sum(rate(fleet_manager_worker_pineapple_duration_bucket{job=\"fleet-manager-metrics\",namespace=\"managed-services-production\",le=\"1800\",jobType=\"pineapple_create\"}[28d]))/sum(rate(fleet_manager_worker_pineapple_duration_count{job=\"fleet-manager-metrics\",namespace=\"managed-services-production\",jobType=\"pineapple_create\"}[28d]))) * 100",
     "legendFormat": "Create Operation"
    }
   ]
  },
  {
   "title": "OSD Cluster Operations Correctness (Non SLO)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 9, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(rate(fleet_manager_cluster_operations_success_count{job=\"fleet-manager-metrics\",namespace=\"managed-services-production\",operation=\"create\"}[5m]))/sum(rate(fleet_manager_cluster_operations_total_count{job=\"fleet-manager-metrics\",namespace=\"managed-services-production\",operation=\"create\"}[5m]))",
     "legendFormat": "Create Operation"
    }
   ]
  },
  {
   "title": "OSD Cluster Operations Latency (Non SLO)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 9, "x": 13, "y": 29 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(fleet_manager_worker_cluster_duration_bucket{job=\"fleet-manager-metrics\",namespace=\"managed-services-production\",le=\"3600\",jobType=\"cluster_create\"}[5m])) by (le))",
     "legendFormat": "p99-create"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(fleet_manager_worker_cluster_duration_bucket{job=\"fleet-manager-metrics\",namespace=\"managed-services-production\",le=\"2400\",jobType=\"cluster_create\"}[5m])) by (le))",
     "legendFormat": "p90-create"
    }
   ]
  }
 ]
}