/*
 * Kafka Service Fleet Manager
 *
 * Kafka Service Fleet Manager is a Rest API to manage kafka instances and connectors.
 *
 * API version: 0.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// AddonClusterTarget Targets workloads to an addon cluster
type AddonClusterTarget struct {
	Kind      string `json:"kind"`
	ClusterId string `json:"cluster_id,omitempty"`
}
