/*
 * Kafka Service Fleet Manager
 *
 * Kafka Service Fleet Manager is a Rest API to manage kafka instances and connectors.
 *
 * API version: 0.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// DataPlaneClusterUpdateStatusRequestResizeInfoDelta struct for DataPlaneClusterUpdateStatusRequestResizeInfoDelta
type DataPlaneClusterUpdateStatusRequestResizeInfoDelta struct {
	IngressEgressThroughputPerSec string `json:"ingressEgressThroughputPerSec,omitempty"`
	Connections                   int32  `json:"connections,omitempty"`
	DataRetentionSize             string `json:"dataRetentionSize,omitempty"`
	MaxPartitions                 int32  `json:"maxPartitions,omitempty"`
}
