/*
 * Kafka Service Fleet Manager
 *
 * Kafka Service Fleet Manager is a Rest API to manage kafka instances and connectors.
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// ManagedKafkaVersions struct for ManagedKafkaVersions
type ManagedKafkaVersions struct {
	Kafka   string `json:"kafka,omitempty"`
	Strimzi string `json:"strimzi,omitempty"`
}
