/*
 * Kafka Service Fleet Manager
 *
 * Kafka Service Fleet Manager is a Rest API to manage kafka instances and connectors.
 *
 * API version: 0.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// ManagedKafkaAllOfAnnotation struct for ManagedKafkaAllOfAnnotation
type ManagedKafkaAllOfAnnotation struct {
	Id          string `json:"id,omitempty"`
	PlacementId string `json:"placementId,omitempty"`
}
