/*
 * Kafka Service Fleet Manager
 *
 * Kafka Service Fleet Manager is a Rest API to manage kafka instances and connectors.
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// ManagedKafkaAllOfMetadataAnnotations struct for ManagedKafkaAllOfMetadataAnnotations
type ManagedKafkaAllOfMetadataAnnotations struct {
	Bf2OrgId          string `json:"bf2.org/id"`
	Bf2OrgPlacementId string `json:"bf2.org/placementId"`
}
