/*
 * Kafka Service Fleet Manager
 *
 * Kafka Service Fleet Manager is a Rest API to manage kafka instances and connectors.
 *
 * API version: 0.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"time"
)

// ConnectorDeploymentAllOfMetadata struct for ConnectorDeploymentAllOfMetadata
type ConnectorDeploymentAllOfMetadata struct {
	CreatedAt       time.Time `json:"created_at,omitempty"`
	UpdatedAt       time.Time `json:"updated_at,omitempty"`
	ResourceVersion int64     `json:"resource_version,omitempty"`
}
