/*
 * Kafka Service Fleet Manager
 *
 * Kafka Service Fleet Manager is a Rest API to manage kafka instances and connectors.
 *
 * API version: 0.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// ConnectorReifyRequest ConnectorReifyRequest is used to create ConnectorDeploymentSpec objects
type ConnectorReifyRequest struct {
	ConnectorId     string                 `json:"connector_id,omitempty"`
	ResourceVersion int64                  `json:"resource_version,omitempty"`
	KafkaId         string                 `json:"kafka_id,omitempty"`
	ClusterId       string                 `json:"cluster_id,omitempty"`
	ClusterStatus   ConnectorClusterStatus `json:"cluster_status,omitempty"`
	ConnectorSpec   map[string]interface{} `json:"connector_spec,omitempty"`
}
