---
# This file contains the role mapping for the admin API based on the HTTP methods.
# Each HTTP method allows configuring an arbitrary amount of roles that authorize requests to the API.
# Each of the role mapping must correspond to an existing Rover group 
# (https://rover.redhat.com/groups/) in order to grant access to the HTTP method containing that role
# Configuration presented below is only used for testing purposes. The actual configuration deployed in 
# production and stage environments will be provided in the saas template in app-interface
- method: GET
  roles:
    - "kas-fleet-manager-admin-full"
    - "kas-fleet-manager-admin-read"
    - "kas-fleet-manager-admin-write"
    - "cos-fleet-manager-admin-read"
    - "cos-fleet-manager-admin-write"
    - "cos-fleet-manager-admin-full"
- method: PATCH
  roles:
    - "kas-fleet-manager-admin-full"
    - "kas-fleet-manager-admin-write"
    - "cos-fleet-manager-admin-write"
    - "cos-fleet-manager-admin-full"
- method: PUT
  roles:
    - "cos-fleet-manager-admin-write"
    - "cos-fleet-manager-admin-full"
- method: POST
  roles:
    - "cos-fleet-manager-admin-full"
- method: DELETE
  roles:
    - "kas-fleet-manager-admin-full"
    - "cos-fleet-manager-admin-full"
