# This configuration defines a list of supported Kafka instance profile and their sizes for KAS Fleet Manager. 
# Modify this file to add additional Kafka instance profiles or sizes or change the values of the default profiles listed below.
# 
# The following properties must be defined for each Kafka profile:
#   - id: Identifier for the Kafka profile. Each profile name should be unique.
#   - sizes: A list of Kafka instance sizes available for this profile (should not be an empty list)
#
# The following properties must be defined for each Kafka instance size (all values must be larger than '0'):
#   - id: The Kafka instance size identifier. Each size id should be unique.
#   - ingressThroughputPerSec: Maximum limit for ingress throughput per second (MB/s).
#   - egressThroughputPerSec: Maximum limit for egress throughput per second (MB/s).
#   - totalMaxConnections: Maximum client connections allowed.
#   - maxConnectionAttemptsPerSec: Maximum client connection attempts per second.
#   - maxDataRetentionSize: Maximum storage (GB).
#   - maxDataRetentionPeriod: Maximum duration(ISO8601) for retaining data.
#   - maxPartitions: Maximum partitions for all topics combined.
#   - cost: Quota cost for selecting this size for a Kafka instance.
---
supported_kafka_sizes:
  - id: standard
    sizes:
    - id: x1
      ingressThroughputPerSec: "50Mi"
      egressThroughputPerSec: "100Mi"
      totalMaxConnections: 3000
      maxConnectionAttemptsPerSec: 100
      maxDataRetentionSize: "1000Gi"
      maxDataRetentionPeriod: "P14D"
      maxPartitions: 1500
      cost: 1
  - id: eval
    sizes:
    - id: x1
      ingressThroughputPerSec: "30Mi"
      egressThroughputPerSec: "30Mi"
      totalMaxConnections: 3000
      maxConnectionAttemptsPerSec: 100
      maxDataRetentionSize: "1000Gi"
      maxDataRetentionPeriod: "P14D"
      maxPartitions: 1000
      cost: 1
