/*
 * Kafka Service Fleet Manager Admin APIs
 *
 * The admin APIs for the fleet manager of Kafka service
 *
 * API version: 0.0.3
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package private

// KafkaAllOfRoutes struct for KafkaAllOfRoutes
type KafkaAllOfRoutes struct {
	Domain string `json:"domain,omitempty"`
	Router string `json:"router,omitempty"`
}
