classDiagram
  
  class ClusterProvider {
      <<Interface>>
      + Create()
      + Get()
      + AddIdentityProvider()
      + ListIdentityProviders()
      + ApplyResources()
      + DeleteResources()
      + ScaleUp()
      + ScaleDown()
      + OtherMethods...()
  }
  class OCMClusterProvider{
      -OCMClient ocmClient
  }
  class StandaloneClusterProvider {

  }
  class ConnectionFactory {
      <<Service>>
  }

  class ClusterService {
      <<Service>>
      + Create()
      + Update()
      + Delete()
      + Find()
      + UpdateStatus()
  }

  class ClusterManager {
      + Reconcile()
  }

  ClusterProvider <|.. OCMClusterProvider: Implements
  ClusterProvider <|.. StandaloneClusterProvider: Implements
  ClusterService ..> ClusterProvider: Depends
  ClusterService ..> ConnectionFactory: Depends
  ClusterManager ..> ClusterService: Depends
