/*
 * Kafka Service Fleet Manager
 *
 * Kafka Service Fleet Manager is a Rest API to manage Kafka instances.
 *
 * API version: 1.4.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package public

// SupportedKafkaSizeBytesValueItem struct for SupportedKafkaSizeBytesValueItem
type SupportedKafkaSizeBytesValueItem struct {
	Bytes float32 `json:"bytes,omitempty"`
}
