/*
 * Kafka Management API
 *
 * Kafka Management API is a REST API to manage Kafka instances
 *
 * API version: 1.12.0
 * Contact: rhosak-support@redhat.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package public

// ServiceAccountList struct for ServiceAccountList
type ServiceAccountList struct {
	Kind  string                   `json:"kind"`
	Items []ServiceAccountListItem `json:"items"`
}
