/*
 * Kafka Management API
 *
 * Kafka Management API is a REST API to manage Kafka instances
 *
 * API version: 1.16.0
 * Contact: rhosak-support@redhat.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package public

// EnterpriseClusterFleetshardParameters Enterprise Cluster fleetshard parameters object
type EnterpriseClusterFleetshardParameters struct {
	// Enterprise Cluster fleetshard parameters array
	FleetshardParameters []FleetshardParameter `json:"fleetshard_parameters,omitempty"`
}
