/*
 * Connector Service Fleet Manager
 *
 * Connector Service Fleet Manager is a Rest API to manage connectors.
 *
 * API version: 0.0.3
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// AddonParameter A addon parameter
type AddonParameter struct {
	Id    string `json:"id,omitempty"`
	Value string `json:"value,omitempty"`
}
