/*
 * Connector Service Fleet Manager Private APIs
 *
 * Connector Service Fleet Manager apis that are used by internal services.
 *
 * API version: 0.0.3
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package private

// ConnectorDeploymentStatusOperators struct for ConnectorDeploymentStatusOperators
type ConnectorDeploymentStatusOperators struct {
	Assigned  ConnectorOperator `json:"assigned,omitempty"`
	Available ConnectorOperator `json:"available,omitempty"`
}
