/*
 * Connector Service Fleet Manager Private APIs
 *
 * Connector Service Fleet Manager apis that are used by internal services.
 *
 * API version: 0.0.3
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package private

// ServiceAccount struct for ServiceAccount
type ServiceAccount struct {
	ClientId     string `json:"client_id"`
	ClientSecret string `json:"client_secret"`
}
