/*
 * Connector Service Fleet Manager Private APIs
 *
 * Connector Service Fleet Manager apis that are used by internal services.
 *
 * API version: 0.0.3
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package private

// DinosaurConnectionSettings struct for DinosaurConnectionSettings
type DinosaurConnectionSettings struct {
	BootstrapServer string `json:"bootstrap_server,omitempty"`
	ClientId        string `json:"client_id,omitempty"`
	ClientSecret    string `json:"client_secret,omitempty"`
}
