/*
 * Connector Service Fleet Manager Private APIs
 *
 * Connector Service Fleet Manager apis that are used by internal services.
 *
 * API version: 0.0.3
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package private

// ConnectorNamespaceStatus Schema for the request to update a data plane namespaces' status
type ConnectorNamespaceStatus struct {
	Id                 string            `json:"id"`
	Phase              string            `json:"phase"`
	Version            string            `json:"version"`
	ConnectorsDeployed int32             `json:"connectors_deployed"`
	Conditions         []MetaV1Condition `json:"conditions,omitempty"`
}
