/*
 * Connector Service Fleet Manager Private APIs
 *
 * Connector Service Fleet Manager apis that are used by internal services.
 *
 * API version: 0.0.3
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package private

// ErrorHandlerLog struct for ErrorHandlerLog
type ErrorHandlerLog struct {
	Log map[string]interface{} `json:"log"`
}
