/*
 * Connector Service Fleet Manager Private APIs
 *
 * Connector Service Fleet Manager apis that are used by internal services.
 *
 * API version: 0.0.3
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package private

// ConnectorNamespaceStatus struct for ConnectorNamespaceStatus
type ConnectorNamespaceStatus struct {
	State              ConnectorNamespaceState `json:"state"`
	Version            string                  `json:"version,omitempty"`
	ConnectorsDeployed int32                   `json:"connectors_deployed"`
	Error              string                  `json:"error,omitempty"`
}
