---
apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: fleet-manager-secrets
  annotations:
    description: "Dinosaur Service Fleet Manager Secrets"
parameters:

- name: DATABASE_TLS_CERT
  description: TLS cert used by the database to encrypt traffic (if ssl mode is on)

- name: DATABASE_HOST
  description: Hostname for the database server.

- name: DATABASE_PORT
  description: Port of the database server.
  value: "5432"

- name: DATABASE_NAME
  description: Name for the database in the server.
  value: fleet-manager

- name: DATABASE_USER
  description: User for the database server.
  value: ocm

- name: DATABASE_PASSWORD
  description: Password for the database user.
  value: TheBlurstOfTimes

- name: OCM_SERVICE_CLIENT_ID
  description: Client id used to interact with other UHC services

- name: OCM_SERVICE_CLIENT_SECRET
  description: Client secret used to interact with other UHC services

- name: OCM_SERVICE_TOKEN
  description: Offline token used to interact with other UHC services

- name: SENTRY_KEY
  description: Private key used in Sentry DSN

- name: AWS_ACCESS_KEY
  description: AWS access key used to create CCS clusters

- name: AWS_ACCOUNT_ID
  description: AWS account id used to create CCS clusters

- name: AWS_SECRET_ACCESS_KEY
  description: AWS secret access key used to create CCS clusters

- name: ROUTE53_ACCESS_KEY
  description: AWS route 53 access key for creating CNAME records

- name: ROUTE53_SECRET_ACCESS_KEY
  description: AWS route 53 secret access key for creating CNAME records

- name: SSO_CLIENT_ID
  description: Client id used to interact with mas sso

- name: SSO_CLIENT_SECRET
  description: Client secret used to interact with mas sso

- name: OSD_IDP_SSO_CLIENT_ID
  description: Client id used to interact with mas sso for configuring osd identity provider

- name: OSD_IDP_SSO_CLIENT_SECRET
  description: Client secret used to interact with mas sso for configuring osd identity provider

- name: DINOSAUR_TLS_CERT
  description: Dinosaur TLS certificate

- name: DINOSAUR_TLS_KEY
  description: Dinosaur TLS certificate private key

- name: OBSERVABILITY_CONFIG_ACCESS_TOKEN
  description: Access token for the observability configuration repo

- name: IMAGE_PULL_DOCKER_CONFIG
  description: Docker config content for pulling private images

- name: KUBE_CONFIG
  description: Kubeconfig content for standalone dataplane clusters communication

- name: OBSERVABILITY_RHSSO_LOGS_CLIENT_ID
  description: Red Hat SSO Logs client id for observability stack

- name: OBSERVABILITY_RHSSO_METRICS_CLIENT_ID
  description: Red Hat SSO Metrics client id for the Observability stack

- name: OBSERVABILITY_RHSSO_LOGS_SECRET
  description: Red Hat SSO Logs secret for the Observability stack

- name: OBSERVABILITY_RHSSO_METRICS_SECRET
  description: Red Hat SSO Metrics secret for the Observability stack

- name: OBSERVABILITY_RHSSO_GRAFANA_CLIENT_ID
  description: Red Hat SSO Grafana client id for the Observability stack

- name: OBSERVABILITY_RHSSO_GRAFANA_CLIENT_SECRET
  description: Red Hat SSO Grafana secret for the Observability stack

objects:

- apiVersion: v1
  kind: Secret
  metadata:
    name: fleet-manager-rds
  stringData:
    db.host: ${DATABASE_HOST}
    db.port: ${DATABASE_PORT}
    db.name: ${DATABASE_NAME}
    db.user: ${DATABASE_USER}
    db.password: ${DATABASE_PASSWORD}
    db.ca_cert: ${DATABASE_TLS_CERT}

- apiVersion: v1
  kind: Secret
  metadata:
    name: fleet-manager
  stringData:
    ocm-service.clientId: ${OCM_SERVICE_CLIENT_ID}
    ocm-service.clientSecret: ${OCM_SERVICE_CLIENT_SECRET}
    ocm-service.token: ${OCM_SERVICE_TOKEN}
    sentry.key: ${SENTRY_KEY}
    aws.accesskey: ${AWS_ACCESS_KEY}
    aws.accountid: ${AWS_ACCOUNT_ID}
    aws.secretaccesskey: ${AWS_SECRET_ACCESS_KEY}
    keycloak-service.clientId: ${SSO_CLIENT_ID}
    keycloak-service.clientSecret: ${SSO_CLIENT_SECRET}
    osd-idp-keycloak-service.clientId: ${OSD_IDP_SSO_CLIENT_ID}
    osd-idp-keycloak-service.clientSecret: ${OSD_IDP_SSO_CLIENT_SECRET}
    aws.route53accesskey: ${ROUTE53_ACCESS_KEY}
    aws.route53secretaccesskey: ${ROUTE53_SECRET_ACCESS_KEY}
    observability-config-access.token: ${OBSERVABILITY_CONFIG_ACCESS_TOKEN}
    image-pull.dockerconfigjson: ${IMAGE_PULL_DOCKER_CONFIG}
    kubeconfig: ${KUBE_CONFIG}

- apiVersion: v1
  kind: Secret
  metadata:
    name: fleet-manager-dataplane-certificate
  stringData:
    tls.crt: ${DINOSAUR_TLS_CERT}
    tls.key: ${DINOSAUR_TLS_KEY}

- apiVersion: v1
  kind: Secret
  metadata:
    name: fleet-manager-observatorium-configuration-red-hat-sso
  stringData:
    logs.clientId: ${OBSERVABILITY_RHSSO_LOGS_CLIENT_ID}
    logs.clientSecret : ${OBSERVABILITY_RHSSO_LOGS_SECRET}
    metrics.clientId: ${OBSERVABILITY_RHSSO_METRICS_CLIENT_ID}
    metrics.clientSecret: ${OBSERVABILITY_RHSSO_METRICS_SECRET}
    grafana.clientId: ${OBSERVABILITY_RHSSO_GRAFANA_CLIENT_ID}
    grafana.clientSecret: ${OBSERVABILITY_RHSSO_GRAFANA_CLIENT_SECRET}
