---
apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: kas-fleet-manager-secrets
  annotations:
    description: "Kafka Service Fleet Manager Secrets"
parameters:

- name: DATABASE_TLS_CERT
  description: TLS cert used by the database to encrypt traffic (if ssl mode is on)

- name: DATABASE_HOST
  description: Hostname for the database server.
  value: "kas-fleet-manager-db"

- name: DATABASE_PORT
  description: Port of the database server.
  value: "5432"

- name: DATABASE_NAME
  description: Name for the database in the server.
  value: kas-fleet-manager

- name: DATABASE_USER
  description: User for the database server.
  value: ocm

- name: DATABASE_PASSWORD
  description: Password for the database user.
  value: TheBlurstOfTimes

- name: OCM_SERVICE_CLIENT_ID
  description: Client id used to interact with other UHC services

- name: OCM_SERVICE_CLIENT_SECRET
  description: Client secret used to interact with other UHC services

- name: OCM_SERVICE_TOKEN
  description: Offline token used to interact with other UHC services

- name: SENTRY_KEY
  description: Private key used in Sentry DSN

- name: AWS_ACCESS_KEY
  description: AWS access key used to create CCS clusters

- name: AWS_ACCOUNT_ID
  description: AWS account id used to create CCS clusters

- name: AWS_SECRET_ACCESS_KEY
  description: AWS secret access key used to create CCS clusters

- name: ROUTE53_ACCESS_KEY
  description: AWS route 53 access key for creating CNAME records

- name: ROUTE53_SECRET_ACCESS_KEY
  description: AWS route 53 secret access key for creating CNAME records

- name: AWS_SECRET_MANAGER_ACCESS_KEY
  description: AWS secret manager access key

- name: AWS_SECRET_MANAGER_SECRET_ACCESS_KEY
  description: AWS secret manager secret access key

- name: MAS_SSO_CLIENT_ID
  description: Client id used to interact with mas sso

- name: MAS_SSO_CLIENT_SECRET
  description: Client secret used to interact with mas sso

- name: OSD_IDP_MAS_SSO_CLIENT_ID
  description: Client id used to interact with mas sso for configuring osd identity provider

- name: OSD_IDP_MAS_SSO_CLIENT_SECRET
  description: Client secret used to interact with mas sso for configuring osd identity provider

- name: MAS_SSO_CRT
  description: tls certificate of the mas sso instance

- name: KAFKA_TLS_CERT
  description: Kafka TLS certificate

- name: ACME_ISSUER_ACCOUNT_KEY
  description: The ACME Issuer account key used for the automatic management of certificate.  

- name: KAFKA_TLS_KEY
  description: Kafka TLS certificate private key

- name: IMAGE_PULL_DOCKER_CONFIG
  description: Docker config content for pulling private images

- name: KUBE_CONFIG
  description: Kubeconfig content for standalone dataplane clusters communication

- name: OBSERVABILITY_RHSSO_GRAFANA_CLIENT_ID
  description: Red Hat SSO Grafana client id for the Observability stack

- name: OBSERVABILITY_RHSSO_GRAFANA_CLIENT_SECRET
  description: Red Hat SSO Grafana secret for the Observability stack

- name: REDHAT_SSO_CLIENT_ID
  description: Client Id used to interact with RedHat SSO

- name: REDHAT_SSO_CLIENT_SECRET
  description:  Client SECRET used to interact with RedHat SSO

- name: GCP_API_CREDENTIALS
  description: Google Cloud Platform (GCP) Credentials in JSON format to access GCP API. See https://cloud.google.com/iam/docs/creating-managing-service-account-keys

- name: OBSERVABILITY_CLOUDWATCHLOGS_CONFIG
  description: Configuration of the Observability CloudWatch Logs. Used by Observability to be able to send Logs to CloudWatch

- name: DATAPLANE_OBSERVABILITY_CONFIG
  description: A yaml file containing the configuration and credentials for the data plane observability stack to push metrics via remote write

objects:

- apiVersion: v1
  kind: Secret
  metadata:
    name: kas-fleet-manager-aws-secret-manager
  stringData:
    aws_access_key_id: ${AWS_SECRET_MANAGER_ACCESS_KEY}
    aws_secret_access_key: ${AWS_SECRET_MANAGER_SECRET_ACCESS_KEY}

- apiVersion: v1
  kind: Secret
  metadata:
    name: kas-fleet-manager-rds
  stringData:
    db.host: ${DATABASE_HOST}
    db.port: ${DATABASE_PORT}
    db.name: ${DATABASE_NAME}
    db.user: ${DATABASE_USER}
    db.password: ${DATABASE_PASSWORD}
    db.ca_cert: ${DATABASE_TLS_CERT}

- apiVersion: v1
  kind: Secret
  metadata:
    name: kas-fleet-manager
  data:
    kubeconfig: ${KUBE_CONFIG}
    image-pull.dockerconfigjson: "${IMAGE_PULL_DOCKER_CONFIG}"
    gcp.api-credentials: "${GCP_API_CREDENTIALS}"
    dataplane-observability-config.yaml: ${DATAPLANE_OBSERVABILITY_CONFIG}
  stringData:
    ocm-service.clientId: ${OCM_SERVICE_CLIENT_ID}
    ocm-service.clientSecret: ${OCM_SERVICE_CLIENT_SECRET}
    ocm-service.token: ${OCM_SERVICE_TOKEN}
    sentry.key: ${SENTRY_KEY}
    aws.accesskey: ${AWS_ACCESS_KEY}
    aws.accountid: ${AWS_ACCOUNT_ID}
    aws.secretaccesskey: ${AWS_SECRET_ACCESS_KEY}
    keycloak-service.clientId: ${MAS_SSO_CLIENT_ID}
    keycloak-service.clientSecret: ${MAS_SSO_CLIENT_SECRET}
    osd-idp-keycloak-service.clientId: ${OSD_IDP_MAS_SSO_CLIENT_ID}
    osd-idp-keycloak-service.clientSecret: ${OSD_IDP_MAS_SSO_CLIENT_SECRET}
    keycloak-service.crt: ${MAS_SSO_CRT}
    aws.route53accesskey: ${ROUTE53_ACCESS_KEY}
    aws.route53secretaccesskey: ${ROUTE53_SECRET_ACCESS_KEY}
    redhatsso-service.clientId: ${REDHAT_SSO_CLIENT_ID}
    redhatsso-service.clientSecret: ${REDHAT_SSO_CLIENT_SECRET}

- apiVersion: v1
  kind: Secret
  metadata:
    name: kas-fleet-manager-dataplane-certificate
  stringData:
    tls.crt: ${KAFKA_TLS_CERT}
    tls.key: ${KAFKA_TLS_KEY}
    kafka-tls-certificate-management-acme-issuer-account-key.pem: ${ACME_ISSUER_ACCOUNT_KEY}

- apiVersion: v1
  kind: Secret
  metadata:
    name: kas-fleet-manager-observability-cwl-config
  data:
    observability-cloudwatchlogs-config.yaml: "${OBSERVABILITY_CLOUDWATCHLOGS_CONFIG}"

- apiVersion: v1
  kind: Secret
  metadata:
    name: kas-fleet-manager-observatorium-configuration-red-hat-sso
  stringData:
    grafana.clientId: ${OBSERVABILITY_RHSSO_GRAFANA_CLIENT_ID}
    grafana.clientSecret: ${OBSERVABILITY_RHSSO_GRAFANA_CLIENT_SECRET}
