/*
 * Pineapple Service Fleet Manager
 *
 * Pineapple Service Fleet Manager APIs that are used by internal services e.g kas-fleetshard operators.
 *
 * API version: 1.3.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package private

// ManagedPineappleList A list of ManagedPineapple CRs
type ManagedPineappleList struct {
	Kind  string             `json:"kind"`
	Items []ManagedPineapple `json:"items"`
}
