/*
 * Dinosaur Service Fleet Manager
 *
 * Dinosaur Service Fleet Manager APIs that are used by internal services e.g fleetshard operators.
 *
 * API version: 1.4.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package private

// ManagedDinosaur struct for ManagedDinosaur
type ManagedDinosaur struct {
	Id       string                       `json:"id,omitempty"`
	Kind     string                       `json:"kind,omitempty"`
	Metadata ManagedDinosaurAllOfMetadata `json:"metadata,omitempty"`
	Spec     ManagedDinosaurAllOfSpec     `json:"spec,omitempty"`
}
