/*
 * Pineapple Service Fleet Manager
 *
 * Pineapple Service Fleet Manager APIs that are used by internal services e.g kas-fleetshard operators.
 *
 * API version: 1.3.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package private

// DataPlanePineappleStatusVersions Version information related to the Pineapple cluster
type DataPlanePineappleStatusVersions struct {
	Pineapple         string `json:"pineapple,omitempty"`
	PineappleOperator string `json:"pineappleOperator,omitempty"`
}
