/*
 * Pineapple Service Fleet Manager
 *
 * Pineapple Service Fleet Manager APIs that are used by internal services e.g kas-fleetshard operators.
 *
 * API version: 1.3.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package private

// ManagedPineappleAllOfMetadataAnnotations struct for ManagedPineappleAllOfMetadataAnnotations
type ManagedPineappleAllOfMetadataAnnotations struct {
	Bf2OrgId          string `json:"bf2.org/id"`
	Bf2OrgPlacementId string `json:"bf2.org/placementId"`
}
