/*
 * Dinosaur Service Fleet Manager
 *
 * Dinosaur Service Fleet Manager APIs that are used by internal services e.g kas-fleetshard operators.
 *
 * API version: 1.3.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package private

// DataPlaneDinosaurStatusVersions Version information related to a Dinosaur cluster
type DataPlaneDinosaurStatusVersions struct {
	Dinosaur string `json:"dinosaur,omitempty"`
	Strimzi  string `json:"strimzi,omitempty"`
}
