/*
 * Dinosaur Service Fleet Manager
 *
 * Dinosaur Service Fleet Manager APIs that are used by internal services e.g fleetshard operators.
 *
 * API version: 1.4.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package private

// DataPlaneDinosaurStatusRoutes struct for DataPlaneDinosaurStatusRoutes
type DataPlaneDinosaurStatusRoutes struct {
	Name   string `json:"name,omitempty"`
	Prefix string `json:"prefix,omitempty"`
	Router string `json:"router,omitempty"`
}
