// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package services

import (
	"github.com/openshift-online/ocm-sdk-go/clustersmgmt/v1"
	"gitlab.cee.redhat.com/service/managed-services-api/pkg/api"
	"gitlab.cee.redhat.com/service/managed-services-api/pkg/errors"
	"sync"
)

var (
	lockClusterServiceMockCreate               sync.RWMutex
	lockClusterServiceMockFindCluster          sync.RWMutex
	lockClusterServiceMockFindClusterByID      sync.RWMutex
	lockClusterServiceMockGetClusterDNS        sync.RWMutex
	lockClusterServiceMockListByStatus         sync.RWMutex
	lockClusterServiceMockScaleDownMachinePool sync.RWMutex
	lockClusterServiceMockScaleUpMachinePool   sync.RWMutex
	lockClusterServiceMockUpdateStatus         sync.RWMutex
)

// Ensure, that ClusterServiceMock does implement ClusterService.
// If this is not the case, regenerate this file with moq.
var _ ClusterService = &ClusterServiceMock{}

// ClusterServiceMock is a mock implementation of ClusterService.
//
//     func TestSomethingThatUsesClusterService(t *testing.T) {
//
//         // make and configure a mocked ClusterService
//         mockedClusterService := &ClusterServiceMock{
//             CreateFunc: func(cluster *api.Cluster) (*v1.Cluster, *errors.ServiceError) {
// 	               panic("mock out the Create method")
//             },
//             FindClusterFunc: func(criteria FindClusterCriteria) (*api.Cluster, *errors.ServiceError) {
// 	               panic("mock out the FindCluster method")
//             },
//             FindClusterByIDFunc: func(clusterID string) (api.Cluster, *errors.ServiceError) {
// 	               panic("mock out the FindClusterByID method")
//             },
//             GetClusterDNSFunc: func(clusterID string) (string, *errors.ServiceError) {
// 	               panic("mock out the GetClusterDNS method")
//             },
//             ListByStatusFunc: func(state api.ClusterStatus) ([]api.Cluster, *errors.ServiceError) {
// 	               panic("mock out the ListByStatus method")
//             },
//             ScaleDownMachinePoolFunc: func(clusterID string) (*v1.MachinePool, *errors.ServiceError) {
// 	               panic("mock out the ScaleDownMachinePool method")
//             },
//             ScaleUpMachinePoolFunc: func(clusterID string) (*v1.MachinePool, *errors.ServiceError) {
// 	               panic("mock out the ScaleUpMachinePool method")
//             },
//             UpdateStatusFunc: func(id string, status api.ClusterStatus) error {
// 	               panic("mock out the UpdateStatus method")
//             },
//         }
//
//         // use mockedClusterService in code that requires ClusterService
//         // and then make assertions.
//
//     }
type ClusterServiceMock struct {
	// CreateFunc mocks the Create method.
	CreateFunc func(cluster *api.Cluster) (*v1.Cluster, *errors.ServiceError)

	// FindClusterFunc mocks the FindCluster method.
	FindClusterFunc func(criteria FindClusterCriteria) (*api.Cluster, *errors.ServiceError)

	// FindClusterByIDFunc mocks the FindClusterByID method.
	FindClusterByIDFunc func(clusterID string) (api.Cluster, *errors.ServiceError)

	// GetClusterDNSFunc mocks the GetClusterDNS method.
	GetClusterDNSFunc func(clusterID string) (string, *errors.ServiceError)

	// ListByStatusFunc mocks the ListByStatus method.
	ListByStatusFunc func(state api.ClusterStatus) ([]api.Cluster, *errors.ServiceError)

	// ScaleDownMachinePoolFunc mocks the ScaleDownMachinePool method.
	ScaleDownMachinePoolFunc func(clusterID string) (*v1.MachinePool, *errors.ServiceError)

	// ScaleUpMachinePoolFunc mocks the ScaleUpMachinePool method.
	ScaleUpMachinePoolFunc func(clusterID string) (*v1.MachinePool, *errors.ServiceError)

	// UpdateStatusFunc mocks the UpdateStatus method.
	UpdateStatusFunc func(id string, status api.ClusterStatus) error

	// calls tracks calls to the methods.
	calls struct {
		// Create holds details about calls to the Create method.
		Create []struct {
			// Cluster is the cluster argument value.
			Cluster *api.Cluster
		}
		// FindCluster holds details about calls to the FindCluster method.
		FindCluster []struct {
			// Criteria is the criteria argument value.
			Criteria FindClusterCriteria
		}
		// FindClusterByID holds details about calls to the FindClusterByID method.
		FindClusterByID []struct {
			// ClusterID is the clusterID argument value.
			ClusterID string
		}
		// GetClusterDNS holds details about calls to the GetClusterDNS method.
		GetClusterDNS []struct {
			// ClusterID is the clusterID argument value.
			ClusterID string
		}
		// ListByStatus holds details about calls to the ListByStatus method.
		ListByStatus []struct {
			// State is the state argument value.
			State api.ClusterStatus
		}
		// ScaleDownMachinePool holds details about calls to the ScaleDownMachinePool method.
		ScaleDownMachinePool []struct {
			// ClusterID is the clusterID argument value.
			ClusterID string
		}
		// ScaleUpMachinePool holds details about calls to the ScaleUpMachinePool method.
		ScaleUpMachinePool []struct {
			// ClusterID is the clusterID argument value.
			ClusterID string
		}
		// UpdateStatus holds details about calls to the UpdateStatus method.
		UpdateStatus []struct {
			// ID is the id argument value.
			ID string
			// Status is the status argument value.
			Status api.ClusterStatus
		}
	}
}

// Create calls CreateFunc.
func (mock *ClusterServiceMock) Create(cluster *api.Cluster) (*v1.Cluster, *errors.ServiceError) {
	if mock.CreateFunc == nil {
		panic("ClusterServiceMock.CreateFunc: method is nil but ClusterService.Create was just called")
	}
	callInfo := struct {
		Cluster *api.Cluster
	}{
		Cluster: cluster,
	}
	lockClusterServiceMockCreate.Lock()
	mock.calls.Create = append(mock.calls.Create, callInfo)
	lockClusterServiceMockCreate.Unlock()
	return mock.CreateFunc(cluster)
}

// CreateCalls gets all the calls that were made to Create.
// Check the length with:
//     len(mockedClusterService.CreateCalls())
func (mock *ClusterServiceMock) CreateCalls() []struct {
	Cluster *api.Cluster
} {
	var calls []struct {
		Cluster *api.Cluster
	}
	lockClusterServiceMockCreate.RLock()
	calls = mock.calls.Create
	lockClusterServiceMockCreate.RUnlock()
	return calls
}

// FindCluster calls FindClusterFunc.
func (mock *ClusterServiceMock) FindCluster(criteria FindClusterCriteria) (*api.Cluster, *errors.ServiceError) {
	if mock.FindClusterFunc == nil {
		panic("ClusterServiceMock.FindClusterFunc: method is nil but ClusterService.FindCluster was just called")
	}
	callInfo := struct {
		Criteria FindClusterCriteria
	}{
		Criteria: criteria,
	}
	lockClusterServiceMockFindCluster.Lock()
	mock.calls.FindCluster = append(mock.calls.FindCluster, callInfo)
	lockClusterServiceMockFindCluster.Unlock()
	return mock.FindClusterFunc(criteria)
}

// FindClusterCalls gets all the calls that were made to FindCluster.
// Check the length with:
//     len(mockedClusterService.FindClusterCalls())
func (mock *ClusterServiceMock) FindClusterCalls() []struct {
	Criteria FindClusterCriteria
} {
	var calls []struct {
		Criteria FindClusterCriteria
	}
	lockClusterServiceMockFindCluster.RLock()
	calls = mock.calls.FindCluster
	lockClusterServiceMockFindCluster.RUnlock()
	return calls
}

// FindClusterByID calls FindClusterByIDFunc.
func (mock *ClusterServiceMock) FindClusterByID(clusterID string) (api.Cluster, *errors.ServiceError) {
	if mock.FindClusterByIDFunc == nil {
		panic("ClusterServiceMock.FindClusterByIDFunc: method is nil but ClusterService.FindClusterByID was just called")
	}
	callInfo := struct {
		ClusterID string
	}{
		ClusterID: clusterID,
	}
	lockClusterServiceMockFindClusterByID.Lock()
	mock.calls.FindClusterByID = append(mock.calls.FindClusterByID, callInfo)
	lockClusterServiceMockFindClusterByID.Unlock()
	return mock.FindClusterByIDFunc(clusterID)
}

// FindClusterByIDCalls gets all the calls that were made to FindClusterByID.
// Check the length with:
//     len(mockedClusterService.FindClusterByIDCalls())
func (mock *ClusterServiceMock) FindClusterByIDCalls() []struct {
	ClusterID string
} {
	var calls []struct {
		ClusterID string
	}
	lockClusterServiceMockFindClusterByID.RLock()
	calls = mock.calls.FindClusterByID
	lockClusterServiceMockFindClusterByID.RUnlock()
	return calls
}

// GetClusterDNS calls GetClusterDNSFunc.
func (mock *ClusterServiceMock) GetClusterDNS(clusterID string) (string, *errors.ServiceError) {
	if mock.GetClusterDNSFunc == nil {
		panic("ClusterServiceMock.GetClusterDNSFunc: method is nil but ClusterService.GetClusterDNS was just called")
	}
	callInfo := struct {
		ClusterID string
	}{
		ClusterID: clusterID,
	}
	lockClusterServiceMockGetClusterDNS.Lock()
	mock.calls.GetClusterDNS = append(mock.calls.GetClusterDNS, callInfo)
	lockClusterServiceMockGetClusterDNS.Unlock()
	return mock.GetClusterDNSFunc(clusterID)
}

// GetClusterDNSCalls gets all the calls that were made to GetClusterDNS.
// Check the length with:
//     len(mockedClusterService.GetClusterDNSCalls())
func (mock *ClusterServiceMock) GetClusterDNSCalls() []struct {
	ClusterID string
} {
	var calls []struct {
		ClusterID string
	}
	lockClusterServiceMockGetClusterDNS.RLock()
	calls = mock.calls.GetClusterDNS
	lockClusterServiceMockGetClusterDNS.RUnlock()
	return calls
}

// ListByStatus calls ListByStatusFunc.
func (mock *ClusterServiceMock) ListByStatus(state api.ClusterStatus) ([]api.Cluster, *errors.ServiceError) {
	if mock.ListByStatusFunc == nil {
		panic("ClusterServiceMock.ListByStatusFunc: method is nil but ClusterService.ListByStatus was just called")
	}
	callInfo := struct {
		State api.ClusterStatus
	}{
		State: state,
	}
	lockClusterServiceMockListByStatus.Lock()
	mock.calls.ListByStatus = append(mock.calls.ListByStatus, callInfo)
	lockClusterServiceMockListByStatus.Unlock()
	return mock.ListByStatusFunc(state)
}

// ListByStatusCalls gets all the calls that were made to ListByStatus.
// Check the length with:
//     len(mockedClusterService.ListByStatusCalls())
func (mock *ClusterServiceMock) ListByStatusCalls() []struct {
	State api.ClusterStatus
} {
	var calls []struct {
		State api.ClusterStatus
	}
	lockClusterServiceMockListByStatus.RLock()
	calls = mock.calls.ListByStatus
	lockClusterServiceMockListByStatus.RUnlock()
	return calls
}

// ScaleDownMachinePool calls ScaleDownMachinePoolFunc.
func (mock *ClusterServiceMock) ScaleDownMachinePool(clusterID string) (*v1.MachinePool, *errors.ServiceError) {
	if mock.ScaleDownMachinePoolFunc == nil {
		panic("ClusterServiceMock.ScaleDownMachinePoolFunc: method is nil but ClusterService.ScaleDownMachinePool was just called")
	}
	callInfo := struct {
		ClusterID string
	}{
		ClusterID: clusterID,
	}
	lockClusterServiceMockScaleDownMachinePool.Lock()
	mock.calls.ScaleDownMachinePool = append(mock.calls.ScaleDownMachinePool, callInfo)
	lockClusterServiceMockScaleDownMachinePool.Unlock()
	return mock.ScaleDownMachinePoolFunc(clusterID)
}

// ScaleDownMachinePoolCalls gets all the calls that were made to ScaleDownMachinePool.
// Check the length with:
//     len(mockedClusterService.ScaleDownMachinePoolCalls())
func (mock *ClusterServiceMock) ScaleDownMachinePoolCalls() []struct {
	ClusterID string
} {
	var calls []struct {
		ClusterID string
	}
	lockClusterServiceMockScaleDownMachinePool.RLock()
	calls = mock.calls.ScaleDownMachinePool
	lockClusterServiceMockScaleDownMachinePool.RUnlock()
	return calls
}

// ScaleUpMachinePool calls ScaleUpMachinePoolFunc.
func (mock *ClusterServiceMock) ScaleUpMachinePool(clusterID string) (*v1.MachinePool, *errors.ServiceError) {
	if mock.ScaleUpMachinePoolFunc == nil {
		panic("ClusterServiceMock.ScaleUpMachinePoolFunc: method is nil but ClusterService.ScaleUpMachinePool was just called")
	}
	callInfo := struct {
		ClusterID string
	}{
		ClusterID: clusterID,
	}
	lockClusterServiceMockScaleUpMachinePool.Lock()
	mock.calls.ScaleUpMachinePool = append(mock.calls.ScaleUpMachinePool, callInfo)
	lockClusterServiceMockScaleUpMachinePool.Unlock()
	return mock.ScaleUpMachinePoolFunc(clusterID)
}

// ScaleUpMachinePoolCalls gets all the calls that were made to ScaleUpMachinePool.
// Check the length with:
//     len(mockedClusterService.ScaleUpMachinePoolCalls())
func (mock *ClusterServiceMock) ScaleUpMachinePoolCalls() []struct {
	ClusterID string
} {
	var calls []struct {
		ClusterID string
	}
	lockClusterServiceMockScaleUpMachinePool.RLock()
	calls = mock.calls.ScaleUpMachinePool
	lockClusterServiceMockScaleUpMachinePool.RUnlock()
	return calls
}

// UpdateStatus calls UpdateStatusFunc.
func (mock *ClusterServiceMock) UpdateStatus(id string, status api.ClusterStatus) error {
	if mock.UpdateStatusFunc == nil {
		panic("ClusterServiceMock.UpdateStatusFunc: method is nil but ClusterService.UpdateStatus was just called")
	}
	callInfo := struct {
		ID     string
		Status api.ClusterStatus
	}{
		ID:     id,
		Status: status,
	}
	lockClusterServiceMockUpdateStatus.Lock()
	mock.calls.UpdateStatus = append(mock.calls.UpdateStatus, callInfo)
	lockClusterServiceMockUpdateStatus.Unlock()
	return mock.UpdateStatusFunc(id, status)
}

// UpdateStatusCalls gets all the calls that were made to UpdateStatus.
// Check the length with:
//     len(mockedClusterService.UpdateStatusCalls())
func (mock *ClusterServiceMock) UpdateStatusCalls() []struct {
	ID     string
	Status api.ClusterStatus
} {
	var calls []struct {
		ID     string
		Status api.ClusterStatus
	}
	lockClusterServiceMockUpdateStatus.RLock()
	calls = mock.calls.UpdateStatus
	lockClusterServiceMockUpdateStatus.RUnlock()
	return calls
}
