/*
 * Kafka Service Fleet Manager
 *
 * Kafka Service Fleet Manager is a Rest API to manage kafka instances and connectors.
 *
 * API version: 1.1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package private

// ManagedKafkaAllOfSpec struct for ManagedKafkaAllOfSpec
type ManagedKafkaAllOfSpec struct {
	Capacity ManagedKafkaCapacity          `json:"capacity,omitempty"`
	Oauth    ManagedKafkaAllOfSpecOauth    `json:"oauth,omitempty"`
	Endpoint ManagedKafkaAllOfSpecEndpoint `json:"endpoint,omitempty"`
	Versions ManagedKafkaVersions          `json:"versions,omitempty"`
	Deleted  bool                          `json:"deleted"`
}
