/*
 * Kafka Service Fleet Manager
 *
 * Kafka Service Fleet Manager APIs that are used by internal services e.g kas-fleetshard operators.
 *
 * API version: 1.1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package private

// DatePlaneClusterUpdateStatusRequestDeprecatedResizeInfoDelta struct for DatePlaneClusterUpdateStatusRequestDeprecatedResizeInfoDelta
type DatePlaneClusterUpdateStatusRequestDeprecatedResizeInfoDelta struct {
	// Deprecated
	DeprecatedIngressEgressThroughputPerSec *string `json:"ingressEgressThroughputPerSec,omitempty"`
	Connections                             *int32  `json:"connections,omitempty"`
	// Deprecated
	DeprecatedDataRetentionSize *string `json:"dataRetentionSize,omitempty"`
	Partitions                  *int32  `json:"partitions,omitempty"`
}
