/*
 * Kafka Service Fleet Manager
 *
 * Kafka Service Fleet Manager is a Rest API to manage kafka instances and connectors.
 *
 * API version: 1.1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package private

// DataPlaneClusterUpdateStatusRequestResizeInfo struct for DataPlaneClusterUpdateStatusRequestResizeInfo
type DataPlaneClusterUpdateStatusRequestResizeInfo struct {
	NodeDelta *int32                                              `json:"node_delta,omitempty"`
	Delta     *DataPlaneClusterUpdateStatusRequestResizeInfoDelta `json:"delta,omitempty"`
}
