/*
 * Kafka Service Fleet Manager
 *
 * Kafka Service Fleet Manager APIs that are used by internal services e.g kas-fleetshard operators.
 *
 * API version: 1.5.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package private

// DatePlaneClusterUpdateStatusRequestNodeInfo struct for DatePlaneClusterUpdateStatusRequestNodeInfo
type DatePlaneClusterUpdateStatusRequestNodeInfo struct {
	Ceiling                *int32 `json:"ceiling,omitempty"`
	Floor                  *int32 `json:"floor,omitempty"`
	Current                *int32 `json:"current,omitempty"`
	CurrentWorkLoadMinimum *int32 `json:"currentWorkLoadMinimum,omitempty"`
}
