/*
 * Kafka Service Fleet Manager
 *
 * Kafka Service Fleet Manager is a Rest API to manage kafka instances and connectors.
 *
 * API version: 1.1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package private

// DataplaneClusterAgentConfigSpec Data plane cluster agent spec
type DataplaneClusterAgentConfigSpec struct {
	Observability DataplaneClusterAgentConfigSpecObservability `json:"observability,omitempty"`
}
