/*
 * Kafka Service Fleet Manager
 *
 * Kafka Service Fleet Manager APIs that are used by internal services e.g kas-fleetshard operators.
 *
 * API version: 1.8.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package private

// DataplaneClusterAgentConfigSpecNet Indicates data plane cluster network configuration
type DataplaneClusterAgentConfigSpecNet struct {
	// Indicates whether the network configuration is private or not
	Private bool `json:"private"`
}
