/*
 * Dinosaur Service Fleet Manager
 *
 * Dinosaur Service Fleet Manager is a Rest API to manage Dinosaur instances.
 *
 * API version: 1.1.2
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package public

// MetricsRangeQueryList struct for MetricsRangeQueryList
type MetricsRangeQueryList struct {
	Kind  string       `json:"kind,omitempty"`
	Id    string       `json:"id,omitempty"`
	Items []RangeQuery `json:"items,omitempty"`
}
