/*
 * Dinosaur Service Fleet Manager
 *
 * Dinosaur Service Fleet Manager is a Rest API to manage Dinosaur instances.
 *
 * API version: 1.1.2
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package public

// ServiceAccountRequest Schema for the request to create a service account
type ServiceAccountRequest struct {
	// The name of the service account
	Name string `json:"name"`
	// A description for the service account
	Description string `json:"description,omitempty"`
}
