/*
 * Dinosaur Service Fleet Manager
 *
 * Dinosaur Service Fleet Manager is a Rest API to manage Dinosaur instances.
 *
 * API version: 1.2.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package public

// ServiceStatusDinosaurs The Dinosaur resource api status
type ServiceStatusDinosaurs struct {
	// Indicates whether we have reached Dinosaur maximum capacity
	MaxCapacityReached bool `json:"max_capacity_reached"`
}
