name: Dispatch Errors Change event
on:
  push:
    branches: 
      - 'main'
    paths:
    - ".github/workflows/errors_update.yaml"
    - "pkg/errors/errors.go"
  
  pull_request:
      types: [opened, synchronize, reopened, ready_for_review]

jobs:
  dispatch:
    # if: github.repository == 'bf2fc6cc711aee1a0c2a/kas-fleet-manager'
    env:
      APP_SERVICES_CI_TOKEN: ${{ secrets.GH_CI_TOKEN }}
    strategy:
      matrix:
        repo:
          - "redhat-developer/app-services-sdk-go"
          - "redhat-developer/app-services-sdk-js"
          - "redhat-developer/app-services-sdk-java"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: KAS Fleet Manager Errors spec Changed
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ env.APP_SERVICES_CI_TOKEN }}
          repository: ${{ matrix.repo }}
          event-type: error-spec-change
          client-payload: '{ "id": "kafka", "download_url":"https://raw.githubusercontent.com/bf2fc6cc711aee1a0c2a/kas-fleet-manager/main/pkg/errors/errors.go"}'
 